import 'package:cloud_firestore/cloud_firestore.dart';

enum Difficulty { easy, medium, hard }

class QuestionModel {
  final String id;
  final String questionText;
  final List<String> options;
  final int correctAnswerIndex;
  final Difficulty difficulty;
  final String category;
  final String createdBy;

  QuestionModel({
    required this.id,
    required this.questionText,
    required this.options,
    required this.correctAnswerIndex,
    required this.difficulty,
    required this.category,
    required this.createdBy,
  });

  Map<String, dynamic> toMap() {
    return {
      'questionText': questionText,
      'options': options,
      'correctAnswerIndex': correctAnswerIndex,
      'difficulty': difficulty.name,
      'category': category,
      'createdBy': createdBy,
    };
  }
}

class Script {
  Future<void> uploadQuestions(List<QuestionModel> questions) async {
    final firestore = FirebaseFirestore.instance;
    for (var q in questions) {
      await firestore.collection('questions').doc(q.id).set(q.toMap());
      print("Uploaded question: ${q.id}");
    }
  }

  void questionadd() async {
    List<QuestionModel> questions = [
      // ===== GEOGRAPHY =====
      QuestionModel(
        id: "q1",
        questionText: "What is the capital of France?",
        options: ["Berlin", "Madrid", "Paris", "Rome"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q2",
        questionText: "Which river is the longest in the world?",
        options: ["Amazon", "Nile", "Yangtze", "Mississippi"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q3",
        questionText: "Mount Everest is located in which mountain range?",
        options: ["Andes", "Himalayas", "Alps", "Rockies"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q4",
        questionText: "Which country has the most natural lakes?",
        options: ["USA", "Canada", "Russia", "Brazil"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q5",
        questionText: "What is the smallest country in the world?",
        options: ["Monaco", "Nauru", "Vatican City", "San Marino"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q6",
        questionText: "Which desert is the largest in the world?",
        options: ["Gobi", "Kalahari", "Sahara", "Arctic"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.medium,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q7",
        questionText: "In which country would you find the city of Timbuktu?",
        options: ["Mali", "Morocco", "Egypt", "Sudan"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.hard,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q8",
        questionText: "Which ocean is the largest?",
        options: ["Atlantic", "Pacific", "Indian", "Arctic"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q9",
        questionText: "What is the capital of Australia?",
        options: ["Sydney", "Melbourne", "Canberra", "Perth"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q10",
        questionText: "Which country is known as the Land of the Rising Sun?",
        options: ["China", "Japan", "Thailand", "South Korea"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Geography",
        createdBy: "system",
      ),

      // ===== SCIENCE =====
      QuestionModel(
        id: "q11",
        questionText: "What is the chemical symbol for water?",
        options: ["O2", "H2O", "CO2", "HO2"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q12",
        questionText: "Which planet is known as the Red Planet?",
        options: ["Earth", "Mars", "Venus", "Jupiter"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q13",
        questionText: "What gas do plants absorb from the atmosphere?",
        options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q14",
        questionText: "Who developed the theory of relativity?",
        options: ["Newton", "Einstein", "Galileo", "Tesla"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q15",
        questionText: "What is the powerhouse of the cell?",
        options: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q16",
        questionText: "What is the speed of light in vacuum?",
        options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000 km/s"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.hard,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q17",
        questionText: "What is the main gas found in Earth's atmosphere?",
        options: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q18",
        questionText: "Which blood type is known as the universal donor?",
        options: ["O-", "O+", "AB+", "AB-"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.medium,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q19",
        questionText: "What is the symbol for gold?",
        options: ["Ag", "Au", "Gd", "Go"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Science",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q20",
        questionText: "Which organ purifies blood in the human body?",
        options: ["Lungs", "Kidneys", "Liver", "Heart"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "Science",
        createdBy: "system",
      ),

      // ===== MATH =====
      QuestionModel(
        id: "q21",
        questionText: "What is 12 × 8?",
        options: ["96", "88", "104", "92"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q22",
        questionText: "What is the square root of 144?",
        options: ["10", "12", "14", "16"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q23",
        questionText: "If x = 5, what is 2x + 3?",
        options: ["10", "13", "15", "8"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q24",
        questionText: "What is 15% of 200?",
        options: ["20", "25", "30", "35"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.medium,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q25",
        questionText: "What is π approximately equal to?",
        options: ["2.14", "3.14", "4.14", "5.14"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q26",
        questionText: "Solve: 7² + 3²",
        options: ["49", "58", "59", "52"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.medium,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q27",
        questionText: "What is the value of log₁₀ 1000?",
        options: ["2", "3", "4", "10"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q28",
        questionText: "Simplify: (2³ × 2²)",
        options: ["2⁵", "2⁶", "2⁴", "2³"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q29",
        questionText: "What is the derivative of x²?",
        options: ["x", "2x", "x²", "2"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.hard,
        category: "Math",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q30",
        questionText: "What is 100 ÷ (4 × 5)?",
        options: ["4", "5", "6", "10"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Math",
        createdBy: "system",
      ),

      // ===== HISTORY =====
      QuestionModel(
        id: "q31",
        questionText: "Who was the first President of the USA?",
        options: [
          "George Washington",
          "Abraham Lincoln",
          "John Adams",
          "Thomas Jefferson",
        ],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q32",
        questionText: "In which year did World War II end?",
        options: ["1945", "1944", "1939", "1950"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q33",
        questionText: "Which empire was ruled by Genghis Khan?",
        options: ["Ottoman", "Mongol", "Roman", "Persian"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q34",
        questionText: "Who discovered America in 1492?",
        options: ["Christopher Columbus", "Vasco da Gama", "Magellan", "Cook"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q35",
        questionText: "The Great Wall is located in which country?",
        options: ["India", "China", "Japan", "Korea"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q36",
        questionText:
            "Which war was fought between the North and South regions in the USA?",
        options: ["WWI", "Civil War", "Vietnam War", "Korean War"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q37",
        questionText: "Who was known as the Iron Lady?",
        options: [
          "Indira Gandhi",
          "Margaret Thatcher",
          "Angela Merkel",
          "Golda Meir",
        ],
        correctAnswerIndex: 1,
        difficulty: Difficulty.medium,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q38",
        questionText: "Which ancient civilization built the pyramids?",
        options: ["Greek", "Egyptian", "Mayan", "Roman"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q39",
        questionText: "In which year did the Berlin Wall fall?",
        options: ["1987", "1988", "1989", "1990"],
        correctAnswerIndex: 2,
        difficulty: Difficulty.medium,
        category: "History",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q40",
        questionText: "Who was the first man to step on the moon?",
        options: [
          "Buzz Aldrin",
          "Neil Armstrong",
          "Yuri Gagarin",
          "Michael Collins",
        ],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "History",
        createdBy: "system",
      ),

      // ===== TECHNOLOGY =====
      QuestionModel(
        id: "q41",
        questionText: "Who is the founder of Microsoft?",
        options: ["Steve Jobs", "Bill Gates", "Mark Zuckerberg", "Larry Page"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q42",
        questionText: "What does 'HTTP' stand for?",
        options: [
          "Hyper Text Transfer Protocol",
          "Hyper Text Translate Protocol",
          "High Transfer Text Protocol",
          "Hyperlink Transfer Text Protocol",
        ],
        correctAnswerIndex: 0,
        difficulty: Difficulty.medium,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q43",
        questionText: "Which company developed the iPhone?",
        options: ["Samsung", "Apple", "Nokia", "Sony"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q44",
        questionText: "What does 'AI' stand for?",
        options: [
          "Artificial Intelligence",
          "Automatic Input",
          "Applied Innovation",
          "Advanced Integration",
        ],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q45",
        questionText:
            "What programming language is used for Android development?",
        options: ["Java", "Swift", "C#", "Kotlin"],
        correctAnswerIndex: 3,
        difficulty: Difficulty.medium,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q46",
        questionText: "What is the brain of a computer?",
        options: ["RAM", "CPU", "Hard Disk", "GPU"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q47",
        questionText: "What does 'URL' stand for?",
        options: [
          "Uniform Resource Locator",
          "Uniform Retrieval Link",
          "Universal Resource Locator",
          "Unified Resource Link",
        ],
        correctAnswerIndex: 0,
        difficulty: Difficulty.medium,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q48",
        questionText: "Which company developed Windows OS?",
        options: ["Microsoft", "Apple", "IBM", "Google"],
        correctAnswerIndex: 0,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q49",
        questionText: "What does 'GPU' stand for?",
        options: [
          "General Processing Unit",
          "Graphics Processing Unit",
          "Graphical Performance Utility",
          "Graphics Power Unit",
        ],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
      QuestionModel(
        id: "q50",
        questionText: "Who founded SpaceX?",
        options: ["Jeff Bezos", "Elon Musk", "Richard Branson", "Bill Gates"],
        correctAnswerIndex: 1,
        difficulty: Difficulty.easy,
        category: "Technology",
        createdBy: "system",
      ),
    ];

    await uploadQuestions(questions);
  }
}
